# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/end-to-end',
                'doc_host': 'https://Analect.github.io',
                'git_url': 'https://github.com/Analect/end-to-end',
                'lib_path': 'end_to_end'},
  'syms': {'end_to_end.core': {'end_to_end.core.foo': ('core.html#foo', 'end_to_end/core.py')}}}